dev:
  app_name: "MS_Local"
  host: "127.0.0.1"
  port: 50051
  consul_addr : "http://127.0.0.1:8500"

  network_interface: "eth2"
  mysql_addr: "127.0.0.1:3306"
  mysql_user: "root"
  mysql_pwd: "Guohao729"
  mysql_db: "software"
  mongodb_addr: "127.0.0.1:27017"
  mongodb_user: ""
  mongodb_pwd: ""
  mongodb_db: "Files"
  mongodb_binary: "binary"
  mongodb_code: "code"

prd:
  app_name: "MS_Local"
  host: "0.0.0.0"
  port: 6001
  #  mongodb_addr: "47.110.79.125:27017"
  #  mysql_addr: "133.133.135.42:3305"
  #  username: "root"
  #  password: "123456"
  #  database: "software"
  mongodb_addr: "127.0.0.1:27017"
  mysql_addr: "127.0.0.1:3306"
  username: "root"
  password: "Guohao729"
  database: "software"
