dev:
  app_name: "sw_ms_local"
  host: "127.0.0.1"
  port: 50051
  consul_addr : "http://127.0.0.1:8500"
  network_interface: "eth2"
  temp_file_path: "D:\\GolangProjects\\src\\test"
#  mysql_addr: "127.0.0.1:3306"
#  mysql_user: "root"
#  mysql_pwd: "Guohao729"
  mysql_addr: "133.133.135.42:3305"
  mysql_user: "root"
  mysql_pwd: "123456"
  mysql_db: "software"
#  mongodb_addr: "mongodb://127.0.0.1:27017"
  mongodb_addr: "mongodb://admin:123456@133.133.135.42:27017"
  mongodb_user: "admin"
  mongodb_pwd: "123456"
  mongodb_db: "Files"
  mongodb_binary: "binary"
  mongodb_code: "code"

prd:
  app_name: "sw_ms_local"
  host: "0.0.0.0"
  port: 50051
  consul_addr : "http://consul_server:8500"
  network_interface: "eth2"
  temp_file_path: "/home/temp"
  mysql_addr: "133.133.135.42:3305"
  mysql_user: "root"
  mysql_pwd: "123456"
  mysql_db: "software"
  mongodb_addr: "mongodb://admin:123456@133.133.135.42:27017"
  mongodb_user: "admin"
  mongodb_pwd: "123456"
  mongodb_db: "Files"
  mongodb_binary: "binary"
  mongodb_code: "code"